import type { Recipe } from "./mealPlanGenerator";

export const EXTRA_LUNCH_RECIPES: Recipe[] = [
  {
    name: "Buddha bowl met quinoa en tahini",
    description: "Voedzame kom met quinoa, geroosterde kikkererwten, spinazie en een nootachtige tahindressing.",
    ingredients: ["150g quinoa", "400g kikkererwten", "100g spinazie", "1 avocado", "1 komkommer", "2 el tahini", "sap van halve citroen", "1 el olijfolie", "2 teentjes knoflook"],
    instructions: ["Kook quinoa gaar en laat afkoelen.", "Rooster kikkererwten 20 min op 200°C met olijfolie en kruiden.", "Meng tahini, citroensap en knoflook met wat water tot dressing.", "Verdeel quinoa over kommen.", "Beleg met kikkererwten, spinazie, avocado en komkommer.", "Besprenkel met tahinidressing."],
  },
  {
    name: "Aziatische kippensalade met sesamdressing",
    description: "Knapperige salade met gegrilde kip, paksoi, wortel en een umami sesamdressing.",
    ingredients: ["200g kipfilet", "1 paksoi", "2 wortelen", "1 rode paprika", "3 el sojasaus", "2 el sesamolie", "1 el honing", "10g sesamzaad", "2 teentjes knoflook"],
    instructions: ["Kruid kipfilet en grill 5-6 min per kant.", "Snipper paksoi, rasp wortel en snijd paprika.", "Meng sojasaus, sesamolie, honing en knoflook tot dressing.", "Laat kip rusten en snijd in plakjes.", "Meng groenten en kip met dressing.", "Bestrooi met sesamzaad."],
  },
  {
    name: "Salade Niçoise",
    description: "Klassieke Franse salade met tonijn, hardgekookt ei, groene boontjes en zwarte olijven.",
    ingredients: ["160g tonijn", "4 eieren", "200g sperziebonen", "250g kerstomaatjes", "40g olijven", "2 el olijfolie", "1 el azijn", "1 tl mosterd", "100g romanosla"],
    instructions: ["Kook eieren 8 minuten en sperziebonen 5 minuten.", "Meng olijfolie, azijn en mosterd tot dressing.", "Verdeel sla over borden.", "Beleg met tonijn, kwartjes ei, boontjes, tomaten en olijven.", "Besprenkel met dressing en serveer."],
  },
  {
    name: "Mexicaanse bonen-rijstbowl",
    description: "Pittige bowl met zwarte bonen, maïs, avocado en verse salsa.",
    ingredients: ["150g zilvervliesrijst", "400g zwarte bonen", "150g mais", "1 avocado", "250g kerstomaatjes", "1 rode ui", "sap van halve limoen", "1 el olijfolie", "koriander"],
    instructions: ["Kook rijst gaar.", "Verwarm zwarte bonen met komijn en chilipoeder.", "Meng tomaten en rode ui met limoen tot salsa.", "Verdeel rijst over kommen.", "Beleg met bonen, mais, avocado en salsa.", "Bestrooi met koriander."],
  },
  {
    name: "Turkse linzensoep",
    description: "Romige rode linzensoep met komijn, paprika en een scheutje citroensap.",
    ingredients: ["200g rode linzen", "1 ui", "2 wortelen", "2 el tomatenpuree", "1 tl komijn", "1 tl paprikapoeder", "1200ml groentebouillon", "sap van halve citroen", "2 el olijfolie"],
    instructions: ["Fruit ui en wortelen 5 min in olijfolie.", "Voeg tomatenpuree en kruiden toe, bak 1 min.", "Voeg linzen en bouillon toe.", "Kook 20-25 min tot linzen gaar zijn.", "Pureer met staafmixer tot gladde soep.", "Breng op smaak met citroensap en serveer."],
  },
  {
    name: "Gerookte zalmwrap met avocado",
    description: "Snelle wrap met gerookte zalm, zachte avocado, rucola en citroenroomkaas.",
    ingredients: ["100g gerookte zalm", "1 avocado", "2 wraps", "50g rucola", "100g roomkaas", "sap van halve citroen", "1 komkommer", "dille"],
    instructions: ["Meng roomkaas met citroensap en dille.", "Smeer roomkaas op de wraps.", "Beleg met rucola en dun gesneden komkommer.", "Verdeel zalm en plakjes avocado erover.", "Rol strak op en snijd diagonaal.", "Direct serveren."],
  },
  {
    name: "Groentefrittata",
    description: "Eiwitrijke Italiaanse oven-omelet met courgette, paprika, spinazie en feta.",
    ingredients: ["6 eieren", "1 courgette", "1 rode paprika", "100g spinazie", "80g fetakaas", "1 ui", "2 el olijfolie", "peterselie, zout, peper"],
    instructions: ["Verwarm oven op 180°C.", "Fruit ui en paprika 5 min in ovenbestendige pan.", "Voeg courgette en spinazie toe, bak 3 min.", "Kluts eieren met peterselie, zout en peper.", "Giet over groenten en strooi feta erover.", "Bak 15-18 min in oven tot stevig."],
  },
  {
    name: "Italiaanse minestrone",
    description: "Hartige Italiaanse groentebouillon met pasta, witte bonen en verse basilicum.",
    ingredients: ["400g witte bonen", "100g volkoren pasta", "2 wortelen", "1 courgette", "400g gepelde tomaten", "1 ui", "100g spinazie", "1400ml groentebouillon", "1 el olijfolie", "basilicum"],
    instructions: ["Fruit ui en wortelen 5 min in olijfolie.", "Voeg tomaten, bouillon en bonen toe.", "Kook 15 min en voeg pasta toe.", "Kook nog 8-10 min.", "Voeg courgette en spinazie toe, kook 3 min.", "Garneer met basilicum en serveer."],
  },
  {
    name: "Kip-broccoli salade met tahindressing",
    description: "Frisse salade met gepocheerde kip, broccoli, edamame en romige tahindressing.",
    ingredients: ["200g kipfilet", "1 broccoli", "150g edamame", "2 el tahini", "2 el sojasaus", "sap van halve citroen", "1 el sesamolie", "10g sesamzaad"],
    instructions: ["Pocheer kipfilet 12 min in licht gezouten water.", "Blancheer broccoli 3 min, spoel af met koud water.", "Meng tahini, sojasaus, citroensap en sesamolie tot dressing.", "Snijd kip in plakjes.", "Combineer kip, broccoli en edamame.", "Besprenkel met dressing en sesamzaad."],
  },
  {
    name: "Mango-garnalensalade",
    description: "Exotische salade met roerbakgarnalen, verse mango, avocado en limoen-chili dressing.",
    ingredients: ["200g garnalen", "200g mango", "1 avocado", "100g rucola", "½ rode ui", "sap van halve limoen", "1 el olijfolie", "1 tl srirachasaus", "koriander"],
    instructions: ["Bak garnalen 2-3 min per kant in olijfolie.", "Snijd mango en avocado in blokjes.", "Meng limoen, sriracha en een scheutje olijfolie tot dressing.", "Verdeel rucola over borden.", "Beleg met mango, avocado, rode ui en garnalen.", "Besprenkel met dressing en koriander."],
  },
  {
    name: "Marokkaanse couscousalade",
    description: "Kleurrijke couscous met gedroogde rozijnen, wortelen, kikkererwten en verse munt.",
    ingredients: ["150g couscous", "400g kikkererwten", "2 wortelen", "50g rozijnen", "2 el olijfolie", "sap van halve citroen", "1 tl komijn", "munt, peterselie", "1 rode ui"],
    instructions: ["Overgiet couscous met kokend water, dek af en laat 5 min staan.", "Rasp wortelen en snipper rode ui.", "Los couscous op met vork en meng met olijfolie.", "Voeg kikkererwten, wortel, rozijnen en ui toe.", "Meng citroensap, komijn en olijfolie tot dressing.", "Garneer met verse munt en peterselie."],
  },
  {
    name: "Soba-noedels met edamame en sesam",
    description: "Japanse boekweitnoedels met edamame, komkommer, wortel en sesamdressing.",
    ingredients: ["150g volkoren pasta", "200g edamame", "1 komkommer", "2 wortelen", "3 el sojasaus", "2 el sesamolie", "1 el azijn", "10g sesamzaad", "2 teentjes knoflook"],
    instructions: ["Kook pasta gaar, spoel af met koud water.", "Blancheer edamame 3 min en spoel af.", "Snijd komkommer en rasp wortelen.", "Meng sojasaus, sesamolie, azijn en knoflook tot dressing.", "Combineer pasta, edamame, komkommer en wortel.", "Besprenkel met dressing en sesamzaad."],
  },
  {
    name: "Volkoren brood met avocado en ei",
    description: "Stevige boterham met gepureerde avocado, gepocheerd ei en chiliflakes.",
    ingredients: ["4 eieren", "2 avocado's", "160g volkorenbrood", "sap van halve citroen", "100g kerstomaatjes", "rucola", "zout, peper"],
    instructions: ["Pocheer eieren 3-4 min in water met scheutje azijn.", "Prak avocado met citroensap, zout en peper.", "Toast het brood.", "Smeer avocado op brood.", "Leg gepocheerde eieren erop.", "Garneer met kerstomaatjes, rucola en peper."],
  },
  {
    name: "Thaise groentewrap met tofu",
    description: "Volkoren wrap met gebakken tofu, paksoi, wortel en een zoet-pittige pindadressing.",
    ingredients: ["200g tofu", "2 wraps", "1 paksoi", "2 wortelen", "3 el pindakaas", "2 el sojasaus", "sap van halve limoen", "1 tl honing", "10g pinda's"],
    instructions: ["Snijd tofu in blokjes en bak goudbruin in beetje olie.", "Meng pindakaas, sojasaus, limoensap en honing met water tot dressing.", "Snijd paksoi en rasp wortelen.", "Leg groenten en tofu op de wraps.", "Besprenkel met pindadressing.", "Bestrooi met pinda's en rol op."],
  },
  {
    name: "Kippensoep Vietnamese stijl",
    description: "Heldere bouillon met kip, rijstnoedels, verse gember en kruiden.",
    ingredients: ["200g kipfilet", "100g rijstnoedels", "1400ml kippenbouillon", "2 wortelen", "gember", "2 teentjes knoflook", "100g spinazie", "sojasaus", "bieslook"],
    instructions: ["Breng bouillon met gember en knoflook aan de kook.", "Voeg kipfilet toe en pocheer 12 min.", "Haal kip eruit en pluk in draden.", "Kook rijstnoedels apart gaar.", "Voeg wortel en spinazie toe aan bouillon.", "Verdeel noedels en kip in kommen, schep hete bouillon erover."],
  },
  {
    name: "Griekse yoghurt bowl met granola",
    description: "Romige kwark met verse bessen, honing, krokante granola en noten.",
    ingredients: ["400g griekse yoghurt", "100g gemengde bessen", "60g granola", "2 tl honing", "30g walnoten", "munt"],
    instructions: ["Verdeel yoghurt over kommen.", "Verdeel bessen erover.", "Bestrooi met granola en walnoten.", "Druppel honing erover.", "Garneer met munt en serveer direct."],
  },
  {
    name: "Warme quinoasalade met gegrilde groenten",
    description: "Voedzame quinoa met geroosterde paprika, courgette en fetakaas.",
    ingredients: ["150g quinoa", "2 paprika's", "1 courgette", "1 aubergine", "80g fetakaas", "2 el olijfolie", "sap van halve citroen", "munt, oregano"],
    instructions: ["Verwarm oven op 200°C.", "Snijd groenten en rooster 20 min met olijfolie en oregano.", "Kook quinoa gaar.", "Meng quinoa met geroosterde groenten.", "Besprenkel met citroensap.", "Bestrooi met verkruimelde feta en munt."],
  },
  {
    name: "Spaanse gazpacho met hummusbrood",
    description: "Koude Spaanse tomatensoep met komkommer, paprika en een boterham met hummus.",
    ingredients: ["600g tomaten", "1 komkommer", "1 rode paprika", "1 rode ui", "2 el olijfolie", "1 el azijn", "1 teentjes knoflook", "160g volkorenbrood", "100g hummus"],
    instructions: ["Snijd alle groenten grof en mix glad met olijfolie, azijn en knoflook.", "Zeef soep voor een gladde textuur.", "Breng op smaak met zout en peper.", "Koel minstens 1 uur in koelkast.", "Toast brood en bestrijk met hummus.", "Schenk koude soep in kommen en serveer met brood."],
  },
  {
    name: "Zalm-avocadobowl met rijst",
    description: "Geïnspireerd op een pokébowl: zalmtartaar met avocado, rijst en sojasaus.",
    ingredients: ["200g zalmfilet", "150g zilvervliesrijst", "1 avocado", "½ komkommer", "3 el sojasaus", "1 el sesamolie", "10g sesamzaad", "1 rode ui", "50g edamame"],
    instructions: ["Kook rijst gaar en laat iets afkoelen.", "Snijd zalm en avocado in blokjes.", "Meng sojasaus en sesamolie tot dressing.", "Verdeel rijst over kommen.", "Beleg met zalm, avocado, komkommer, ui en edamame.", "Besprenkel met dressing en sesamzaad."],
  },
  {
    name: "Linzen-wortelsoep met kokos",
    description: "Zachte soep van rode linzen en wortel met een scheutje kokosmelk en verse koriander.",
    ingredients: ["180g rode linzen", "3 wortelen", "1 ui", "200ml kokosmelk", "1000ml groentebouillon", "1 tl kurkuma", "1 tl komijn", "2 teentjes knoflook", "1 el olijfolie", "koriander"],
    instructions: ["Fruit ui en knoflook in olijfolie.", "Voeg wortel, linzen, kurkuma en komijn toe.", "Voeg bouillon toe en kook 20 min.", "Voeg kokosmelk toe en pureer.", "Breng op smaak en verwarm zacht.", "Garneer met koriander en serveer."],
  },
  // --- BONUS ---
  {
    name: "Caprese salade met kip",
    description: "Frisse caprese met gegrilde kip, mozzarella, tomaten en verse basilicum.",
    ingredients: ["200g kipfilet", "200g tomaten", "125g mozzarella", "40g rucola", "2 el olijfolie", "azijn", "basilicum", "zout, peper"],
    instructions: ["Grill kipfilet 5-6 min per kant.", "Snijd tomaten en mozzarella.", "Schik rucola op borden.", "Verdeel tomaten en mozzarella erover.", "Beleg met gesneden kip.", "Besprenkel met olijfolie en azijn."],
  },
  {
    name: "Bonenburrito bowl",
    description: "Stevige bowl met kidneybonen, rijst, avocado, salsa en Griekse yoghurt.",
    ingredients: ["150g rijst", "400g kidneybonen", "1 avocado", "250g kerstomaatjes", "1 rode ui", "100g griekse yoghurt", "sap van halve limoen", "1 el olijfolie", "koriander"],
    instructions: ["Kook rijst gaar.", "Verwarm kidneybonen met komijn en chilipoeder.", "Meng tomaten en rode ui met limoensap tot salsa.", "Verdeel rijst over kommen.", "Beleg met bonen, avocado, salsa en een lepel yoghurt.", "Bestrooi met koriander."],
  },
  {
    name: "Pittige kipcurrysoep",
    description: "Lichte Aziatische soep met kip, kokosmelk, citroengras en paksoi.",
    ingredients: ["200g kipfilet", "300ml kokosmelk", "800ml kippenbouillon", "1 paksoi", "2 wortelen", "2 el currypasta", "2 teentjes knoflook", "gember", "rijstnoedels 100g", "koriander"],
    instructions: ["Breng bouillon met currypasta, knoflook en gember aan de kook.", "Voeg kip toe en kook 12 min, haal eruit en pluk.", "Voeg kokosmelk, wortel en paksoi toe.", "Kook rijstnoedels apart gaar.", "Voeg geplukde kip terug.", "Verdeel noedels in kommen, schep soep erbij en garneer met koriander."],
  },
  {
    name: "Courgettespaghetti met pesto en tonijn",
    description: "Lichte courgetteslierten als pasta met tonijn, pesto en cherrytomaten.",
    ingredients: ["2 courgettes", "160g tonijn", "250g kerstomaatjes", "2 el pijnboompitten", "parmezaan 30g", "2 el olijfolie", "2 teentjes knoflook", "basilicum", "sap van halve citroen"],
    instructions: ["Maak courgetteslierten met dunschiller of spiralizer.", "Bak knoflook en kerstomaatjes 3 min in olijfolie.", "Voeg courgetteslierten toe, roerbak 2 min.", "Meng met tonijn en citroensap.", "Bestrooi met pijnboompitten en parmezaan.", "Garneer met basilicum."],
  },
];

export const EXTRA_DINNER_RECIPES: Recipe[] = [
  {
    name: "Marokkaanse kip met couscous",
    description: "Gekruide kip met kikkererwten, gedroogde rozijnen en geurige couscous.",
    ingredients: ["300g kipfilet", "400g kikkererwten", "180g couscous", "50g rozijnen", "2 wortelen", "1 ui", "1 tl ras el hanout", "1 tl komijn", "2 el olijfolie", "koriander"],
    instructions: ["Bak ui en wortelen 5 min in olijfolie.", "Voeg kip en kruiden toe, bak rondom bruin.", "Voeg kikkererwten en 250ml water toe, sudder 15 min.", "Voeg rozijnen toe en verwarm door.", "Bereid couscous met kokend water.", "Serveer kip met couscous en garneer met koriander."],
  },
  {
    name: "Thaise groene curry met kip",
    description: "Romige kokoscurry met kipfilet, broccoli, paprika en zilvervliesrijst.",
    ingredients: ["300g kipfilet", "300ml kokosmelk", "200ml groentebouillon", "1 broccoli", "1 rode paprika", "2 el currypasta", "180g zilvervliesrijst", "2 teentjes knoflook", "koriander"],
    instructions: ["Kook rijst gaar.", "Bak knoflook en currypasta 1 min.", "Voeg kip toe en bak goudbruin.", "Voeg kokosmelk en bouillon toe, sudder 10 min.", "Voeg broccoli en paprika toe, kook 5 min.", "Serveer curry op rijst, garneer met koriander."],
  },
  {
    name: "Teriyaki zalm met rijst en broccoli",
    description: "Geglazuurde zalmfilet met zoetige teriyakisaus, broccoli en rijst.",
    ingredients: ["300g zalmfilet", "180g zilvervliesrijst", "1 broccoli", "3 el teriyakisaus", "1 el sesamolie", "10g sesamzaad", "2 teentjes knoflook"],
    instructions: ["Kook rijst gaar.", "Blancheer broccoli 4 min.", "Bak zalm 3 min per kant in sesamolie.", "Voeg teriyakisaus en knoflook toe, glaceer 2 min.", "Serveer zalm op rijst met broccoli.", "Bestrooi met sesamzaad."],
  },
  {
    name: "Indiase dal met rijst",
    description: "Hartig Indiaas linzenstoofpotje met kurkuma, komijn en verse koriander.",
    ingredients: ["200g rode linzen", "400g gepelde tomaten", "300ml kokosmelk", "1 ui", "3 teentjes knoflook", "gember", "1 tl kurkuma", "1 tl komijn", "180g rijst", "koriander"],
    instructions: ["Bak ui, knoflook en gember 5 min.", "Voeg kurkuma en komijn toe, roer 1 min.", "Voeg tomaten, linzen en 400ml water toe.", "Sudder 20 min tot linzen gaar zijn.", "Roer kokosmelk erdoor.", "Kook rijst en serveer dal erop, bestrooi met koriander."],
  },
  {
    name: "Mexicaanse kipfajitas met rijst",
    description: "Gekruide kipstrips met paprika, mais en rijst in een pittige kruidenmix.",
    ingredients: ["300g kipfilet", "2 paprika's", "150g mais", "180g rijst", "1 ui", "1 tl komijn", "1 el olijfolie", "100g griekse yoghurt", "koriander", "sap van halve limoen"],
    instructions: ["Kook rijst gaar.", "Snijd kip in reepjes, kruid met komijn en paprikapoeder.", "Bak ui en paprika 5 min in olijfolie.", "Voeg kip toe en bak gaar.", "Voeg mais toe en verwarm.", "Serveer op rijst met yoghurt, limoensap en koriander."],
  },
  {
    name: "Provençaalse ratatouille met quinoa",
    description: "Langzaam gegaarde ratatouille met aubergine, courgette, paprika en quinoa.",
    ingredients: ["1 aubergine", "2 courgettes", "2 paprika's", "400g gepelde tomaten", "1 ui", "3 teentjes knoflook", "180g quinoa", "2 el olijfolie", "basilicum, oregano"],
    instructions: ["Snijd groenten in blokjes.", "Bak ui en knoflook 5 min in olijfolie.", "Voeg aubergine en courgette toe, bak 5 min.", "Voeg tomaten, paprika en kruiden toe.", "Sudder 25 min op laag vuur.", "Serveer ratatouille op gekookte quinoa."],
  },
  {
    name: "Griekse ovenschotel met kip en groenten",
    description: "Mediterraan ovengerecht met kip, aardappelen, tomaten, olijven en feta.",
    ingredients: ["300g kipfilet", "400g aardappelen", "250g kerstomaatjes", "40g olijven", "80g fetakaas", "2 el olijfolie", "oregano", "sap van halve citroen", "2 teentjes knoflook"],
    instructions: ["Verwarm oven op 200°C.", "Snijd kip en aardappelen.", "Meng alles behalve feta met olijfolie, knoflook en oregano.", "Schik op bakplaat en bak 30 min.", "Bestrooi met feta en bak nog 5 min.", "Besprenkel met citroensap en serveer."],
  },
  {
    name: "Aziatische rundvleeswok met rijst",
    description: "Snelle wokschotel met mals rundvlees, paksoi, shiitake en oestersaus.",
    ingredients: ["300g rundergehakt", "1 paksoi", "150g shiitake", "180g zilvervliesrijst", "3 el sojasaus", "1 el sesamolie", "2 teentjes knoflook", "gember", "10g sesamzaad"],
    instructions: ["Kook rijst gaar.", "Verhit wok op hoog vuur met sesamolie.", "Bak gehakt rul en drooggebakken, zet apart.", "Wok knoflook, gember, paksoi en shiitake 3 min.", "Voeg gehakt en sojasaus terug, roerbak 2 min.", "Serveer op rijst, bestrooi met sesamzaad."],
  },
  {
    name: "Kip satay met sperziebonen en rijst",
    description: "Gegrilde kipspiesjes met pindamasaus, sperziebonen en zilvervliesrijst.",
    ingredients: ["300g kipfilet", "200g sperziebonen", "180g zilvervliesrijst", "3 el pindakaas", "2 el sojasaus", "1 el honing", "sap van halve limoen", "10g sesamzaad"],
    instructions: ["Kook rijst en blancheer sperziebonen 4 min.", "Snijd kip in blokjes en rijg op spiesjes.", "Grill kip 5-6 min per kant.", "Meng pindakaas, sojasaus, honing en limoensap met heet water tot saus.", "Serveer kip op rijst met sperziebonen.", "Schenk pindamasaus erover en bestrooi met sesamzaad."],
  },
  {
    name: "Italiaanse gevulde courgette",
    description: "Uitgehaalde courgettes gevuld met tonijn, rijst, tomaten en mozzarella.",
    ingredients: ["2 courgettes", "160g tonijn", "150g rijst", "250g kerstomaatjes", "100g mozzarella", "1 ui", "2 teentjes knoflook", "2 el olijfolie", "basilicum"],
    instructions: ["Verwarm oven op 190°C.", "Halveer courgettes en hol uit.", "Bak ui en knoflook, meng met tonijn, gekookte rijst en tomaten.", "Vul courgettes met mengsel.", "Beleg met mozzarella en bak 20 min.", "Garneer met basilicum."],
  },
  {
    name: "Kip met citroengras en kokos",
    description: "Aromatische Zuidoost-Aziatische kip met kokosmelk, citroengras, gember en rijst.",
    ingredients: ["300g kipfilet", "300ml kokosmelk", "200ml kippenbouillon", "180g zilvervliesrijst", "2 wortelen", "gember", "3 teentjes knoflook", "sojasaus", "koriander"],
    instructions: ["Kook rijst gaar.", "Bak knoflook en gember 2 min.", "Snijd kip in blokjes en bak rondom bruin.", "Voeg kokosmelk, bouillon en wortel toe.", "Sudder 15 min tot kip gaar is.", "Serveer op rijst en garneer met koriander."],
  },
  {
    name: "Turks auberginestoofpotje met gehakt",
    description: "Rijke stoofschotel van aubergine, gehakt, tomaten en kruiden met couscous.",
    ingredients: ["300g rundergehakt", "1 aubergine", "400g gepelde tomaten", "1 ui", "2 paprika's", "3 teentjes knoflook", "2 el olijfolie", "180g couscous", "komijn, paprikapoeder"],
    instructions: ["Snijd aubergine in blokjes, bestuif met zout en dep droog.", "Bak ui, knoflook en paprika's 5 min.", "Voeg gehakt toe en bak rul.", "Voeg aubergine, tomaten en kruiden toe, sudder 20 min.", "Bereid couscous met kokend water.", "Serveer stoofpotje op couscous."],
  },
  {
    name: "Spaanse kip met groene olijven en rijst",
    description: "Sappige stoofkip met groene olijven, tomaten, paprika en zilvervliesrijst.",
    ingredients: ["300g kipfilet", "40g olijven", "400g gepelde tomaten", "1 ui", "1 rode paprika", "3 teentjes knoflook", "2 el olijfolie", "180g zilvervliesrijst", "paprikapoeder, oregano"],
    instructions: ["Kook rijst gaar.", "Bak kip rondom bruin in olijfolie, zet apart.", "Bak ui, paprika en knoflook 5 min.", "Voeg tomaten, olijven en kruiden toe.", "Leg kip terug en sudder 20 min.", "Serveer op rijst."],
  },
  {
    name: "Vegetarische kikkererwten-spinaziecurry",
    description: "Romige curry met kikkererwten, spinazie, tomaten en zacht gekookte basmatirijst.",
    ingredients: ["400g kikkererwten", "300g spinazie", "400g gepelde tomaten", "200ml kokosmelk", "1 ui", "3 teentjes knoflook", "gember", "1 tl kurkuma", "1 tl komijn", "180g rijst"],
    instructions: ["Bak ui, knoflook en gember 5 min.", "Voeg kurkuma en komijn toe, roer 1 min.", "Voeg tomaten, kikkererwten en kokosmelk toe, sudder 15 min.", "Voeg spinazie toe en laat slinken.", "Kook rijst gaar.", "Serveer curry op rijst."],
  },
  {
    name: "Gegratineerde zalm met aardappelen",
    description: "Romige ovenzalm met gestoofde spinazie, geroosterde aardappelen en dille.",
    ingredients: ["300g zalmfilet", "400g aardappelen", "200g spinazie", "100g griekse yoghurt", "1 ui", "2 el olijfolie", "dille", "sap van halve citroen", "30g parmezaan"],
    instructions: ["Verwarm oven op 200°C.", "Snijd aardappelen en rooster 20 min.", "Bak spinazie met ui tot geslonken.", "Leg zalm op een bakplaat, kruid met dille en citroensap.", "Smeer yoghurt over zalm, bestrooi met parmezaan.", "Bak 15-18 min en serveer met aardappelen en spinazie."],
  },
  {
    name: "Kipfilet met pesto, tomaat en volkoren pasta",
    description: "Klassieke Italiaanse pasta met gegrilde kip, zelfgemaakte pestosaus en cherrytomaten.",
    ingredients: ["250g kipfilet", "180g volkoren pasta", "250g kerstomaatjes", "30g pijnboompitten", "30g parmezaan", "50g basilicum", "2 el olijfolie", "2 teentjes knoflook"],
    instructions: ["Kook pasta gaar.", "Mix basilicum, pijnboompitten, parmezaan, knoflook en olijfolie tot pesto.", "Grill kip 5-6 min per kant en snijd in plakjes.", "Halveer kerstomaatjes en bak kort.", "Meng warme pasta met pesto.", "Serveer met kip en tomaten."],
  },
  {
    name: "Japanse miso-kipschotel met rijst",
    description: "Geglazuurde kip met misosaus, edamame en gestoomde broccoli op rijst.",
    ingredients: ["300g kipfilet", "180g zilvervliesrijst", "1 broccoli", "150g edamame", "2 el misopasta", "1 el honing", "2 el sojasaus", "1 el sesamolie", "10g sesamzaad"],
    instructions: ["Kook rijst en stoom broccoli gaar.", "Meng misopasta, honing en sojasaus tot glasuur.", "Bak kip in sesamolie 5 min per kant.", "Smeer glasuur over kip en bak nog 3 min.", "Blancheer edamame 3 min.", "Serveer op rijst met broccoli en edamame, bestrooi met sesamzaad."],
  },
  {
    name: "Vegetarische ovenpaprika met bulgur",
    description: "Kleurrijke paprika's gevuld met bulgur, spinazie, feta en zongedroogde tomaten.",
    ingredients: ["4 paprika's", "150g bulgur", "200g spinazie", "80g fetakaas", "1 ui", "2 teentjes knoflook", "2 el olijfolie", "50g pijnboompitten", "peterselie"],
    instructions: ["Verwarm oven op 190°C.", "Halveer paprika's en verwijder zaadjes.", "Kook bulgur gaar.", "Bak ui en knoflook, voeg spinazie toe en laat slinken.", "Meng bulgur, spinazie en pijnboompitten.", "Vul paprika's en bestrooi met feta.", "Bak 20-25 min."],
  },
  {
    name: "Gegrilde kabeljauw met aardappelwiggen",
    description: "Sappige kabeljauw met kruiden, geroosterde aardappelwiggen en een frisse yoghurtsaus.",
    ingredients: ["300g kabeljauwfilet", "400g aardappelen", "200g sperziebonen", "150g griekse yoghurt", "sap van halve citroen", "2 el olijfolie", "dille", "2 teentjes knoflook"],
    instructions: ["Verwarm oven op 200°C.", "Snijd aardappelen in wiggen en rooster 25 min.", "Kruid kabeljauw met dille, zout en citroensap.", "Bak vis 4 min per kant in olijfolie.", "Blancheer sperziebonen 4 min.", "Meng yoghurt met knoflook en citroen tot saus.", "Serveer vis met aardappelwiggen en boontjes."],
  },
  {
    name: "Wokschotel garnalen met glasnoedels",
    description: "Snel gerechtje met sappige garnalen, glasnoedels, paksoi en een pittige sojasaus.",
    ingredients: ["250g garnalen", "120g glasnoedels", "1 paksoi", "1 rode paprika", "3 el sojasaus", "1 el sesamolie", "2 teentjes knoflook", "gember", "10g sesamzaad", "koriander"],
    instructions: ["Week glasnoedels 5 min in warm water, giet af.", "Verhit wok met sesamolie op hoog vuur.", "Wok knoflook en gember 1 min.", "Voeg garnalen toe en bak 2-3 min.", "Voeg paksoi en paprika toe, wok 3 min.", "Voeg noedels en sojasaus toe, roerbak 2 min.", "Bestrooi met sesamzaad en koriander."],
  },
];
